###
GET http://localhost:8080/comment/list?page=1&size=20

###
POST http://localhost:8080/comment/save
Content-Type: application/json

{
  "vid": 101,
  "uid": 1009,
  "rootId": 0,
  "parentId": 0,
  "toUserId": 0,
  "content": "广告内容",
  "love": 0,
  "bad": 10,
  "createTime": "2024-05-20 14:55:00",
  "isTop": 0,
  "isDeleted": 1
}

###
###
GET http://localhost:8080/comment/getcomment/3/10/1

###