###
GET http://localhost:8080/user/list?page=1&size=20

###
POST http://localhost:8080/user/loading
Content-Type: application/json

{
  "username": "Jacqueline Griffin",
  "password": "4WSZ1ivAHP"
}

###
###
POST http://localhost:8080/user/save
Content-Type: application/json

{
  "username": "22221",
  "password": "1234",
  "nickname": "1231",
  "gender": 1

}

###
###
GET http://localhost:8080/user/info/2

###